// Generated by bun run generate:sdks. Do not edit.
using System.Net.Http; using System.Text.Json;
namespace Zad.Tools.Uaemcp;
public sealed class UaemcpClient {
 private readonly string _baseUrl; private readonly HttpClient _http; public UaemcpClient(string baseUrl="https://uaemcp.zad.tools", HttpClient? http=null){_baseUrl=baseUrl.TrimEnd('/');_http=http??new HttpClient{Timeout=TimeSpan.FromSeconds(20)};}
 private async Task<JsonDocument> Get(string path, IReadOnlyDictionary<string,string?>? parameters, CancellationToken cancellationToken){var query=parameters is null?"":string.Join("&",parameters.Where(x=>x.Value is not null).Select(x=>$"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value!)}")); using var response=await _http.GetAsync(_baseUrl+path+(query.Length>0?"?"+query:""),cancellationToken); var body=await response.Content.ReadAsStringAsync(cancellationToken); if(!response.IsSuccessStatusCode)throw new HttpRequestException($"UAEMCP HTTP {(int)response.StatusCode}: {body}"); return JsonDocument.Parse(body);}
 public Task<JsonDocument> GetCoverage(IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/coverage",parameters,cancellationToken);
 public Task<JsonDocument> ListSources(IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/sources",parameters,cancellationToken);
 public Task<JsonDocument> Search(IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/search",parameters,cancellationToken);
 public Task<JsonDocument> GetRecords(string SourceId, IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/sources/" + Uri.EscapeDataString(SourceId) + "/records",parameters,cancellationToken);
 public Task<JsonDocument> GetDatasetSchema(string SourceId, IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/sources/" + Uri.EscapeDataString(SourceId) + "/schema",parameters,cancellationToken);
 public Task<JsonDocument> ListRecipes(IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/intelligence/recipes",parameters,cancellationToken);
 public Task<JsonDocument> GetTileJson(string SourceId, IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/sources/" + Uri.EscapeDataString(SourceId) + "/tilejson",parameters,cancellationToken);
 public Task<JsonDocument> SpatialJoin(IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("/api/v1/spatial/join",parameters,cancellationToken);
}
