// Code generated by bun run generate:sdks. DO NOT EDIT.
package uaemcp

import ("context"; "encoding/json"; "fmt"; "io"; "net/http"; "net/url"; "strings"; "time")
type Client struct { BaseURL string; HTTP *http.Client }
func New(baseURL string) *Client { return &Client{strings.TrimRight(baseURL, "/"), &http.Client{Timeout: 20*time.Second}} }
func (c *Client) get(ctx context.Context, path string, params url.Values) (map[string]any, error) {
 u := c.BaseURL + path; if len(params)>0 { u += "?" + params.Encode() }; req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil); if err != nil{return nil,err}; req.Header.Set("Accept","application/json")
 res, err := c.HTTP.Do(req); if err != nil{return nil,err}; defer res.Body.Close(); body, err := io.ReadAll(res.Body); if err != nil{return nil,err}; if res.StatusCode>=400{return nil,fmt.Errorf("uaemcp HTTP %d: %s",res.StatusCode,string(body))}; var out map[string]any; err=json.Unmarshal(body,&out); return out,err
}
func (c *Client) ListProducts(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/products", params) }
func (c *Client) GetPolicyEvidenceWatch(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/policy-watch", params) }
func (c *Client) CheckPolicyEvidenceWatch(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/policy-watch/check", params) }
func (c *Client) GetPolicyEvidenceWatchOperations(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/operations/policy-watch", params) }
func (c *Client) BuildEvidenceDossier(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/evidence-dossier", params) }
func (c *Client) GetNationalEvidenceBrief(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/national-brief", params) }
func (c *Client) SearchPlaceNames(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/places", params) }
func (c *Client) BuildFounderPathway(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/founder-pathway", params) }
func (c *Client) GetGoldenResidencyPathways(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/golden-residency", params) }
func (c *Client) AssessGoldenResidencyReadiness(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/golden-residency/assess", params) }
func (c *Client) GetBusinessSetupCatalogue(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/business-setup", params) }
func (c *Client) RouteBusinessSetup(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/business-setup/route", params) }
func (c *Client) GetStartupSupportCatalogue(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/startup-support", params) }
func (c *Client) MatchStartupSupport(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/startup-support/match", params) }
func (c *Client) GetEducationLedger(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/education", params) }
func (c *Client) GetHealthIndicators(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/health-indicators", params) }
func (c *Client) GetHealthFacilitiesAtlas(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/health-facilities", params) }
func (c *Client) GetCoverage(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/coverage", params) }
func (c *Client) GetIndustryAtlas(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/industry-atlas", params) }
func (c *Client) GetIndustryChange(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/industry-atlas/change", params) }
func (c *Client) GetTradeFlowRadar(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/trade-flow", params) }
func (c *Client) GetAjmanBusinessEvidence(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/ajman-business", params) }
func (c *Client) GetAjmanUrbanEvidence(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/ajman-urban", params) }
func (c *Client) GetAjmanParksFootfall(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/ajman-parks", params) }
func (c *Client) GetTaxServiceActivity2025(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/tax-services", params) }
func (c *Client) GetTaxServiceArchive(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/tax-services/archive", params) }
func (c *Client) ListSources(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources", params) }
func (c *Client) Search(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/search", params) }
func (c *Client) GetRecords(ctx context.Context, SourceId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources/" + url.PathEscape(SourceId) + "/records", params) }
func (c *Client) GetDatasetSchema(ctx context.Context, SourceId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources/" + url.PathEscape(SourceId) + "/schema", params) }
func (c *Client) ListRecipes(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/intelligence/recipes", params) }
func (c *Client) ListIndicators(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/intelligence/indicators", params) }
func (c *Client) GetIndicator(ctx context.Context, IndicatorId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/intelligence/indicators/" + url.PathEscape(IndicatorId) + "", params) }
func (c *Client) GetObservatoryReport(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/observatory", params) }
func (c *Client) ListObservatoryIncidents(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/observatory/incidents", params) }
func (c *Client) GetObservatorySource(ctx context.Context, SourceId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/observatory/sources/" + url.PathEscape(SourceId) + "", params) }
func (c *Client) GetTileJson(ctx context.Context, SourceId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources/" + url.PathEscape(SourceId) + "/tilejson", params) }
func (c *Client) SpatialJoin(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/spatial/join", params) }
func (c *Client) ResolveEntities(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/entities/resolve", params) }
