// Code generated by bun run generate:sdks. DO NOT EDIT.
package uaemcp

import ("context"; "encoding/json"; "fmt"; "io"; "net/http"; "net/url"; "strings"; "time")
type Client struct { BaseURL string; HTTP *http.Client }
func New(baseURL string) *Client { return &Client{strings.TrimRight(baseURL, "/"), &http.Client{Timeout: 20*time.Second}} }
func (c *Client) get(ctx context.Context, path string, params url.Values) (map[string]any, error) {
 u := c.BaseURL + path; if len(params)>0 { u += "?" + params.Encode() }; req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil); if err != nil{return nil,err}; req.Header.Set("Accept","application/json")
 res, err := c.HTTP.Do(req); if err != nil{return nil,err}; defer res.Body.Close(); body, err := io.ReadAll(res.Body); if err != nil{return nil,err}; if res.StatusCode>=400{return nil,fmt.Errorf("uaemcp HTTP %d: %s",res.StatusCode,string(body))}; var out map[string]any; err=json.Unmarshal(body,&out); return out,err
}
func (c *Client) GetCoverage(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/coverage", params) }
func (c *Client) ListSources(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources", params) }
func (c *Client) Search(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/search", params) }
func (c *Client) GetRecords(ctx context.Context, SourceId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources/" + url.PathEscape(SourceId) + "/records", params) }
func (c *Client) GetDatasetSchema(ctx context.Context, SourceId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources/" + url.PathEscape(SourceId) + "/schema", params) }
func (c *Client) ListRecipes(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/intelligence/recipes", params) }
func (c *Client) GetTileJson(ctx context.Context, SourceId string, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/sources/" + url.PathEscape(SourceId) + "/tilejson", params) }
func (c *Client) SpatialJoin(ctx context.Context, params url.Values) (map[string]any,error) { return c.get(ctx, "/api/v1/spatial/join", params) }
