// Generated by bun run generate:sdks. Do not edit.
package tools.zad.uaemcp;
import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.Map; import java.util.stream.Collectors;
public final class UaemcpClient {
 private final String baseUrl; private final HttpClient http = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(20)).build();
 public UaemcpClient(String baseUrl){this.baseUrl=baseUrl.replaceAll("/+$","");} private static String enc(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8).replace("+","%20");}
 private String get(String path, Map<String,String> params) throws Exception {String q=params.entrySet().stream().filter(e->e.getValue()!=null).map(e->enc(e.getKey())+"="+enc(e.getValue())).collect(Collectors.joining("&")); HttpRequest r=HttpRequest.newBuilder(URI.create(baseUrl+path+(q.isEmpty()?"":"?"+q))).timeout(Duration.ofSeconds(20)).header("Accept","application/json").build(); HttpResponse<String> s=http.send(r,HttpResponse.BodyHandlers.ofString()); if(s.statusCode()>=400)throw new IllegalStateException("UAEMCP HTTP "+s.statusCode()+": "+s.body()); return s.body();}
 public String listProducts(Map<String,String> params) throws Exception {return get("/api/v1/products",params);}
 public String buildFounderPathway(Map<String,String> params) throws Exception {return get("/api/v1/founder-pathway",params);}
 public String getGoldenResidencyPathways(Map<String,String> params) throws Exception {return get("/api/v1/golden-residency",params);}
 public String assessGoldenResidencyReadiness(Map<String,String> params) throws Exception {return get("/api/v1/golden-residency/assess",params);}
 public String getBusinessSetupCatalogue(Map<String,String> params) throws Exception {return get("/api/v1/business-setup",params);}
 public String routeBusinessSetup(Map<String,String> params) throws Exception {return get("/api/v1/business-setup/route",params);}
 public String getStartupSupportCatalogue(Map<String,String> params) throws Exception {return get("/api/v1/startup-support",params);}
 public String matchStartupSupport(Map<String,String> params) throws Exception {return get("/api/v1/startup-support/match",params);}
 public String getEducationLedger(Map<String,String> params) throws Exception {return get("/api/v1/education",params);}
 public String getHealthIndicators(Map<String,String> params) throws Exception {return get("/api/v1/health-indicators",params);}
 public String getCoverage(Map<String,String> params) throws Exception {return get("/api/v1/coverage",params);}
 public String getIndustryAtlas(Map<String,String> params) throws Exception {return get("/api/v1/industry-atlas",params);}
 public String getIndustryChange(Map<String,String> params) throws Exception {return get("/api/v1/industry-atlas/change",params);}
 public String getTradeFlowRadar(Map<String,String> params) throws Exception {return get("/api/v1/trade-flow",params);}
 public String getTaxServiceActivity2025(Map<String,String> params) throws Exception {return get("/api/v1/tax-services",params);}
 public String getTaxServiceArchive(Map<String,String> params) throws Exception {return get("/api/v1/tax-services/archive",params);}
 public String listSources(Map<String,String> params) throws Exception {return get("/api/v1/sources",params);}
 public String search(Map<String,String> params) throws Exception {return get("/api/v1/search",params);}
 public String getRecords(String SourceId, Map<String,String> params) throws Exception {return get("/api/v1/sources/" + enc(SourceId) + "/records",params);}
 public String getDatasetSchema(String SourceId, Map<String,String> params) throws Exception {return get("/api/v1/sources/" + enc(SourceId) + "/schema",params);}
 public String listRecipes(Map<String,String> params) throws Exception {return get("/api/v1/intelligence/recipes",params);}
 public String listIndicators(Map<String,String> params) throws Exception {return get("/api/v1/intelligence/indicators",params);}
 public String getIndicator(String IndicatorId, Map<String,String> params) throws Exception {return get("/api/v1/intelligence/indicators/" + enc(IndicatorId) + "",params);}
 public String getObservatoryReport(Map<String,String> params) throws Exception {return get("/api/v1/observatory",params);}
 public String listObservatoryIncidents(Map<String,String> params) throws Exception {return get("/api/v1/observatory/incidents",params);}
 public String getObservatorySource(String SourceId, Map<String,String> params) throws Exception {return get("/api/v1/observatory/sources/" + enc(SourceId) + "",params);}
 public String getTileJson(String SourceId, Map<String,String> params) throws Exception {return get("/api/v1/sources/" + enc(SourceId) + "/tilejson",params);}
 public String spatialJoin(Map<String,String> params) throws Exception {return get("/api/v1/spatial/join",params);}
 public String resolveEntities(Map<String,String> params) throws Exception {return get("/api/v1/entities/resolve",params);}
}
