// Generated by bun run generate:sdks. Do not edit.
use serde_json::Value;
pub struct UaemcpClient { base_url: String, http: reqwest::Client }
impl UaemcpClient {
 pub fn new(base_url: &str) -> Self { Self { base_url: base_url.trim_end_matches('/').into(), http: reqwest::Client::new() } }
 async fn get(&self, path: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.http.get(format!("{}{}",self.base_url,path)).query(params).send().await?.error_for_status()?.json().await }
 pub async fn list_products(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/products"), params).await }
 pub async fn list_mcp_tools(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/tools"), params).await }
 pub async fn get_policy_evidence_watch(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/policy-watch"), params).await }
 pub async fn check_policy_evidence_watch(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/policy-watch/check"), params).await }
 pub async fn get_policy_evidence_watch_operations(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/operations/policy-watch"), params).await }
 pub async fn build_evidence_dossier(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/evidence-dossier"), params).await }
 pub async fn get_national_evidence_brief(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/national-brief"), params).await }
 pub async fn get_connectivity_pulse(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/connectivity"), params).await }
 pub async fn get_tourism_pulse(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/tourism-pulse"), params).await }
 pub async fn search_place_names(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/places"), params).await }
 pub async fn build_founder_pathway(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/founder-pathway"), params).await }
 pub async fn get_golden_residency_pathways(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/golden-residency"), params).await }
 pub async fn assess_golden_residency_readiness(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/golden-residency/assess"), params).await }
 pub async fn get_business_setup_catalogue(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/business-setup"), params).await }
 pub async fn route_business_setup(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/business-setup/route"), params).await }
 pub async fn get_startup_support_catalogue(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/startup-support"), params).await }
 pub async fn match_startup_support(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/startup-support/match"), params).await }
 pub async fn get_education_ledger(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/education"), params).await }
 pub async fn get_health_indicators(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/health-indicators"), params).await }
 pub async fn get_health_facilities_atlas(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/health-facilities"), params).await }
 pub async fn get_health_facilities_map(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/health-facilities-map"), params).await }
 pub async fn get_aeronautical_publications(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/aeronautical-publications"), params).await }
 pub async fn get_coverage(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/coverage"), params).await }
 pub async fn get_industry_atlas(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/industry-atlas"), params).await }
 pub async fn get_industry_change(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/industry-atlas/change"), params).await }
 pub async fn get_trade_flow_radar(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/trade-flow"), params).await }
 pub async fn get_ajman_business_evidence(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/ajman-business"), params).await }
 pub async fn get_ajman_urban_evidence(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/ajman-urban"), params).await }
 pub async fn get_ajman_parks_footfall(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/ajman-parks"), params).await }
 pub async fn get_tax_service_activity2025(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/tax-services"), params).await }
 pub async fn get_tax_service_archive(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/tax-services/archive"), params).await }
 pub async fn list_sources(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources"), params).await }
 pub async fn search(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/search"), params).await }
 pub async fn get_records(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/records", urlencoding::encode(source_id)), params).await }
 pub async fn get_dataset_schema(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/schema", urlencoding::encode(source_id)), params).await }
 pub async fn list_recipes(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/intelligence/recipes"), params).await }
 pub async fn list_indicators(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/intelligence/indicators"), params).await }
 pub async fn get_indicator(&self, indicator_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/intelligence/indicators/{}", urlencoding::encode(indicator_id)), params).await }
 pub async fn get_observatory_report(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/observatory"), params).await }
 pub async fn list_observatory_incidents(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/observatory/incidents"), params).await }
 pub async fn get_observatory_source(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/observatory/sources/{}", urlencoding::encode(source_id)), params).await }
 pub async fn get_tile_json(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/tilejson", urlencoding::encode(source_id)), params).await }
 pub async fn spatial_join(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/spatial/join"), params).await }
 pub async fn resolve_entities(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/entities/resolve"), params).await }
}
