// Generated by bun run generate:sdks. Do not edit.
use serde_json::Value;
pub struct UaemcpClient { base_url: String, http: reqwest::Client }
impl UaemcpClient {
 pub fn new(base_url: &str) -> Self { Self { base_url: base_url.trim_end_matches('/').into(), http: reqwest::Client::new() } }
 async fn get(&self, path: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.http.get(format!("{}{}",self.base_url,path)).query(params).send().await?.error_for_status()?.json().await }
 pub async fn get_coverage(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/coverage"), params).await }
 pub async fn list_sources(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources"), params).await }
 pub async fn search(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/search"), params).await }
 pub async fn get_records(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/records", urlencoding::encode(source_id)), params).await }
 pub async fn get_dataset_schema(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/schema", urlencoding::encode(source_id)), params).await }
 pub async fn list_recipes(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/intelligence/recipes"), params).await }
 pub async fn get_tile_json(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/tilejson", urlencoding::encode(source_id)), params).await }
 pub async fn spatial_join(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/spatial/join"), params).await }
}
