// Generated by bun run generate:sdks. Do not edit.
use serde_json::Value;
pub struct UaemcpClient { base_url: String, http: reqwest::Client }
impl UaemcpClient {
 pub fn new(base_url: &str) -> Self { Self { base_url: base_url.trim_end_matches('/').into(), http: reqwest::Client::new() } }
 async fn get(&self, path: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.http.get(format!("{}{}",self.base_url,path)).query(params).send().await?.error_for_status()?.json().await }
 pub async fn get_coverage(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/coverage"), params).await }
 pub async fn get_industry_atlas(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/industry-atlas"), params).await }
 pub async fn get_industry_change(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/industry-atlas/change"), params).await }
 pub async fn get_trade_flow_radar(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/trade-flow"), params).await }
 pub async fn get_tax_service_activity2025(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/tax-services"), params).await }
 pub async fn get_tax_service_archive(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/tax-services/archive"), params).await }
 pub async fn list_sources(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources"), params).await }
 pub async fn search(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/search"), params).await }
 pub async fn get_records(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/records", urlencoding::encode(source_id)), params).await }
 pub async fn get_dataset_schema(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/schema", urlencoding::encode(source_id)), params).await }
 pub async fn list_recipes(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/intelligence/recipes"), params).await }
 pub async fn list_indicators(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/intelligence/indicators"), params).await }
 pub async fn get_indicator(&self, indicator_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/intelligence/indicators/{}", urlencoding::encode(indicator_id)), params).await }
 pub async fn get_observatory_report(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/observatory"), params).await }
 pub async fn list_observatory_incidents(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/observatory/incidents"), params).await }
 pub async fn get_observatory_source(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/observatory/sources/{}", urlencoding::encode(source_id)), params).await }
 pub async fn get_tile_json(&self, source_id: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/sources/{}/tilejson", urlencoding::encode(source_id)), params).await }
 pub async fn spatial_join(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/spatial/join"), params).await }
 pub async fn resolve_entities(&self, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("/api/v1/entities/resolve"), params).await }
}
