import { mkdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { openApiDocument } from "../src/openapi.js";

type Operation = { id: string; path: string; pathParams: string[] };
const root = resolve(import.meta.dir, "..");
const document = openApiDocument("https://uaemcp.zad.tools") as any;
const operations: Operation[] = Object.entries(document.paths).flatMap(([path, item]: [string, any]) => Object.values(item).map((operation: any) => ({
  id: operation.operationId,
  path,
  pathParams: (operation.parameters ?? []).filter((parameter: any) => parameter.in === "path").map((parameter: any) => parameter.name),
})));

const snake = (value: string) => value.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
const pascal = (value: string) => value.replace(/(^|_)(\w)/g, (_match, _prefix, char) => char.toUpperCase());
const pathExpression = (operation: Operation, language: "python" | "go" | "rust" | "java" | "csharp"): string => {
  let path = operation.path;
  for (const name of operation.pathParams) {
    const variable = language === "python" || language === "rust" ? snake(name) : language === "go" ? pascal(snake(name)) : pascal(snake(name));
    path = path.replace(`{${name}}`, language === "python" ? `{quote(str(${variable}), safe='')}` : language === "rust" ? `{}` : language === "go" ? `" + url.PathEscape(${variable}) + "` : language === "java" ? `" + enc(${variable}) + "` : `" + Uri.EscapeDataString(${variable}) + "`);
  }
  return path;
};

const python = `# Generated by bun run generate:sdks. Do not edit.
from json import loads
from urllib.parse import urlencode, quote
from urllib.request import Request, urlopen

class UaemcpError(RuntimeError):
    pass

class UaemcpClient:
    def __init__(self, base_url="https://uaemcp.zad.tools", timeout=20):
        self.base_url, self.timeout = base_url.rstrip("/"), timeout

    def _get(self, path, params=None):
        query = urlencode({k: v for k, v in (params or {}).items() if v is not None}).replace("%2C", ",")
        request = Request(self.base_url + path + (("?" + query) if query else ""), headers={"Accept": "application/json", "User-Agent": "uaemcp-python/${document.info.version}"})
        with urlopen(request, timeout=self.timeout) as response:
            payload = loads(response.read())
        if isinstance(payload, dict) and payload.get("ok") is False:
            raise UaemcpError(payload.get("error", {}).get("message", "UAEMCP request failed"))
        return payload
${operations.map((operation) => `
    def ${snake(operation.id)}(self, ${operation.pathParams.map((name) => `${snake(name)}, `).join("")}**params):
        return self._get(f"${pathExpression(operation, "python")}", params)`).join("\n")}
`;

const go = `// Code generated by bun run generate:sdks. DO NOT EDIT.
package uaemcp

import ("context"; "encoding/json"; "fmt"; "io"; "net/http"; "net/url"; "strings"; "time")
type Client struct { BaseURL string; HTTP *http.Client }
func New(baseURL string) *Client { return &Client{strings.TrimRight(baseURL, "/"), &http.Client{Timeout: 20*time.Second}} }
func (c *Client) get(ctx context.Context, path string, params url.Values) (map[string]any, error) {
 u := c.BaseURL + path; if len(params)>0 { u += "?" + params.Encode() }; req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil); if err != nil{return nil,err}; req.Header.Set("Accept","application/json")
 res, err := c.HTTP.Do(req); if err != nil{return nil,err}; defer res.Body.Close(); body, err := io.ReadAll(res.Body); if err != nil{return nil,err}; if res.StatusCode>=400{return nil,fmt.Errorf("uaemcp HTTP %d: %s",res.StatusCode,string(body))}; var out map[string]any; err=json.Unmarshal(body,&out); return out,err
}
${operations.map((operation) => `func (c *Client) ${pascal(snake(operation.id))}(ctx context.Context, ${operation.pathParams.map((name) => `${pascal(snake(name))} string, `).join("")}params url.Values) (map[string]any,error) { return c.get(ctx, "${pathExpression(operation, "go")}", params) }`).join("\n")}
`;

const rust = `// Generated by bun run generate:sdks. Do not edit.
use serde_json::Value;
pub struct UaemcpClient { base_url: String, http: reqwest::Client }
impl UaemcpClient {
 pub fn new(base_url: &str) -> Self { Self { base_url: base_url.trim_end_matches('/').into(), http: reqwest::Client::new() } }
 async fn get(&self, path: &str, params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.http.get(format!("{}{}",self.base_url,path)).query(params).send().await?.error_for_status()?.json().await }
${operations.map((operation) => ` pub async fn ${snake(operation.id)}(&self, ${operation.pathParams.map((name) => `${snake(name)}: &str, `).join("")}params: &[(&str,&str)]) -> Result<Value, reqwest::Error> { self.get(&format!("${pathExpression(operation, "rust")}"${operation.pathParams.map((name) => `, urlencoding::encode(${snake(name)})`).join("")}), params).await }`).join("\n")}
}
`;

const java = `// Generated by bun run generate:sdks. Do not edit.
package tools.zad.uaemcp;
import java.net.*; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.Map; import java.util.stream.Collectors;
public final class UaemcpClient {
 private final String baseUrl; private final HttpClient http = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(20)).build();
 public UaemcpClient(String baseUrl){this.baseUrl=baseUrl.replaceAll("/+$","");} private static String enc(String v){return URLEncoder.encode(v,StandardCharsets.UTF_8).replace("+","%20");}
 private String get(String path, Map<String,String> params) throws Exception {String q=params.entrySet().stream().filter(e->e.getValue()!=null).map(e->enc(e.getKey())+"="+enc(e.getValue())).collect(Collectors.joining("&")); HttpRequest r=HttpRequest.newBuilder(URI.create(baseUrl+path+(q.isEmpty()?"":"?"+q))).timeout(Duration.ofSeconds(20)).header("Accept","application/json").build(); HttpResponse<String> s=http.send(r,HttpResponse.BodyHandlers.ofString()); if(s.statusCode()>=400)throw new IllegalStateException("UAEMCP HTTP "+s.statusCode()+": "+s.body()); return s.body();}
${operations.map((operation) => ` public String ${operation.id}(${operation.pathParams.map((name) => `String ${pascal(snake(name))}, `).join("")}Map<String,String> params) throws Exception {return get("${pathExpression(operation, "java")}",params);}`).join("\n")}
}
`;

const csharp = `// Generated by bun run generate:sdks. Do not edit.
using System.Net.Http; using System.Text.Json;
namespace Zad.Tools.Uaemcp;
public sealed class UaemcpClient {
 private readonly string _baseUrl; private readonly HttpClient _http; public UaemcpClient(string baseUrl="https://uaemcp.zad.tools", HttpClient? http=null){_baseUrl=baseUrl.TrimEnd('/');_http=http??new HttpClient{Timeout=TimeSpan.FromSeconds(20)};}
 private async Task<JsonDocument> Get(string path, IReadOnlyDictionary<string,string?>? parameters, CancellationToken cancellationToken){var query=parameters is null?"":string.Join("&",parameters.Where(x=>x.Value is not null).Select(x=>$"{Uri.EscapeDataString(x.Key)}={Uri.EscapeDataString(x.Value!)}")); using var response=await _http.GetAsync(_baseUrl+path+(query.Length>0?"?"+query:""),cancellationToken); var body=await response.Content.ReadAsStringAsync(cancellationToken); if(!response.IsSuccessStatusCode)throw new HttpRequestException($"UAEMCP HTTP {(int)response.StatusCode}: {body}"); return JsonDocument.Parse(body);}
${operations.map((operation) => ` public Task<JsonDocument> ${pascal(snake(operation.id))}(${operation.pathParams.map((name) => `string ${pascal(snake(name))}, `).join("")}IReadOnlyDictionary<string,string?>? parameters=null, CancellationToken cancellationToken=default)=>Get("${pathExpression(operation, "csharp")}",parameters,cancellationToken);`).join("\n")}
}
`;

const files: Record<string, string> = {
  "sdk/python/uaemcp/client.py": python, "sdk/go/client.go": go, "sdk/rust/src/lib.rs": rust,
  "sdk/java/src/main/java/tools/zad/uaemcp/UaemcpClient.java": java, "sdk/csharp/UaemcpClient.cs": csharp,
  "sdk/python/pyproject.toml": `[project]\nname = "uaemcp"\nversion = "${document.info.version}"\nrequires-python = ">=3.10"\ndescription = "Generated Python client for Open Emirates Intelligence"\n[build-system]\nrequires = ["setuptools>=68"]\nbuild-backend = "setuptools.build_meta"\n`,
  "sdk/python/uaemcp/__init__.py": `from .client import UaemcpClient, UaemcpError\n__all__ = ["UaemcpClient", "UaemcpError"]\n`,
  "sdk/go/go.mod": `module github.com/zad-tools/uaemcp/sdk/go\n\ngo 1.22\n`,
  "sdk/rust/Cargo.toml": `[package]\nname = "uaemcp"\nversion = "${document.info.version}"\nedition = "2021"\ndescription = "Generated Rust client for Open Emirates Intelligence"\nlicense = "MIT"\n[dependencies]\nreqwest = { version = "0.12", features = ["json"] }\nserde_json = "1"\nurlencoding = "2"\n`,
  "sdk/java/pom.xml": `<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>tools.zad</groupId><artifactId>uaemcp-client</artifactId><version>${document.info.version}</version><properties><maven.compiler.release>17</maven.compiler.release></properties></project>\n`,
  "sdk/csharp/Uaemcp.csproj": `<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><Version>${document.info.version}</Version></PropertyGroup></Project>\n`,
};
let stale = false;
for (const [relative, content] of Object.entries(files)) {
  const path = resolve(root, relative); const normalized = content.trimStart();
  if (process.argv.includes("--check")) { try { if (readFileSync(path, "utf8") !== normalized) stale = true; } catch { stale = true; } }
  else { mkdirSync(dirname(path), { recursive: true }); await Bun.write(path, normalized); }
}
if (stale) { console.error("Generated SDKs are stale. Run: bun run generate:sdks"); process.exit(1); }
if (!process.argv.includes("--check")) console.log(`Generated ${Object.keys(files).length} SDKs from OpenAPI ${document.info.version}`);
