import { VERSION } from "./version.js";
import { GOLDEN_PATHWAY_IDS } from "./golden-residency.js";
import { BUSINESS_ACTIVITY_SECTORS, BUSINESS_EMIRATES, BUSINESS_SETUP_TYPES } from "./business-setup.js";
import { STARTUP_EMIRATES, STARTUP_STAGES, STARTUP_SUPPORT_TYPES } from "./startup-support.js";
import { EVIDENCE_DOSSIER_TEMPLATES, EVIDENCE_PILLAR_IDS } from "./evidence-dossier.js";
import { POLICY_WATCH_SOURCE_IDS } from "./policy-watch-service.js";

const envelope = (schema: Record<string, unknown>): Record<string, unknown> => ({
  type: "object", required: ["ok", "data", "error", "meta"],
  properties: { ok: { type: "boolean" }, data: schema, error: { anyOf: [{ type: "object" }, { type: "null" }] }, meta: { type: "object", additionalProperties: true } },
});

const parameter = (name: string, required = false, schema: Record<string, unknown> = { type: "string" }): Record<string, unknown> => ({ name, in: "query", required, schema });
const response = (schema: Record<string, unknown>): Record<string, unknown> => ({ description: "Successful response", content: { "application/json": { schema } } });
const nonNegative = { type: "number", minimum: 0 };
const goldenAssessmentSchema = {
  type: "object", required: ["pathway"], additionalProperties: false,
  properties: {
    pathway: { type: "string", enum: [...GOLDEN_PATHWAY_IDS] },
    jurisdiction: { type: "string", enum: ["federal", "dubai", "abu_dhabi"], default: "federal" },
    capitalAed: nonNegative, propertyValueAed: nonNegative, annualTaxAed: nonNegative, projectValueAed: nonNegative,
    innovativeProjectEvidence: { type: "boolean" }, incubatorRecommendation: { type: "boolean" }, professionalRecommendation: { type: "boolean" },
    attestedDegree: { type: "boolean" }, fiveYearsExperience: { type: "boolean" }, employmentContract: { type: "boolean" }, monthlySalaryAed: nonNegative, validPassportEvidence: { type: "boolean" },
    gradePercent: { type: "number", minimum: 0, maximum: 100 }, universityGpa: { type: "number", minimum: 0, maximum: 4 }, graduatedWithinTwoYears: { type: "boolean" }, ministryRecommendation: { type: "boolean" }, universityRecommendation: { type: "boolean" },
    humanitarianYears: nonNegative, volunteerHours: nonNegative, humanitarianSupportAed: nonNegative,
  },
};
const businessSetupRouteSchema = { type: "object", required: ["emirate", "setupType"], additionalProperties: false, properties: { emirate: { type: "string", enum: [...BUSINESS_EMIRATES] }, setupType: { type: "string", enum: [...BUSINESS_SETUP_TYPES] }, activitySector: { type: "string", enum: [...BUSINESS_ACTIVITY_SECTORS] } } };
const startupSupportMatchSchema = { type: "object", required: ["stage", "supportType", "emirate"], additionalProperties: false, properties: { stage: { type: "string", enum: [...STARTUP_STAGES] }, supportType: { type: "string", enum: [...STARTUP_SUPPORT_TYPES] }, emirate: { type: "string", enum: [...STARTUP_EMIRATES] } } };
const founderPathwaySchema = { type: "object", required: ["stage", "emirate", "setupType", "supportType"], additionalProperties: false, properties: { stage: { type: "string", enum: [...STARTUP_STAGES] }, emirate: { type: "string", enum: [...BUSINESS_EMIRATES] }, setupType: { type: "string", enum: [...BUSINESS_SETUP_TYPES] }, supportType: { type: "string", enum: [...STARTUP_SUPPORT_TYPES] }, activitySector: { type: "string", enum: [...BUSINESS_ACTIVITY_SECTORS] } } };
const evidenceDossierSchema = { type: "object", required: ["template", "question", "language", "pillars"], additionalProperties: false, properties: { template: { type: "string", enum: [...EVIDENCE_DOSSIER_TEMPLATES] }, question: { type: "string", minLength: 1, maxLength: 200 }, language: { type: "string", enum: ["en", "ar"] }, pillars: { type: "array", minItems: 2, maxItems: 5, uniqueItems: true, items: { type: "string", enum: [...EVIDENCE_PILLAR_IDS] } }, query: { type: "string", maxLength: 100 }, emirate: { type: "string", enum: [...BUSINESS_EMIRATES] }, healthFacilitiesLimit: { type: "integer", minimum: 1, maximum: 200 }, healthIndicatorsLimit: { type: "integer", minimum: 1, maximum: 50 }, industryLimit: { type: "integer", minimum: 1, maximum: 100 } } };
const policyWatchCheckSchema = { type: "object", additionalProperties: false, properties: { sourceIds: { type: "array", minItems: 1, maxItems: 5, uniqueItems: true, items: { type: "string", enum: [...POLICY_WATCH_SOURCE_IDS] } } } };

export function openApiDocument(origin = "http://localhost:8080"): Record<string, unknown> {
  const sourceId = { name: "sourceId", in: "path", required: true, schema: { type: "string" } };
  return {
    openapi: "3.1.0",
    info: { title: "Open Emirates Intelligence API", version: VERSION, description: "Source-cited official UAE open data. Unknown or unavailable data is never fabricated.", license: { name: "MIT" } },
    servers: [{ url: origin }],
    tags: [{ name: "Products" }, { name: "Catalog" }, { name: "Data" }, { name: "Intelligence" }, { name: "Observatory" }, { name: "Maps" }],
    paths: {
      "/api/v1/products": { get: { operationId: "listProducts", tags: ["Products"], responses: { "200": response(envelope({ type: "array", items: { $ref: "#/components/schemas/Product" } })) } } },
      "/api/v1/tools": { get: { operationId: "listMcpTools", tags: ["Catalog"], responses: { "200": response(envelope({ $ref: "#/components/schemas/ToolCatalog" })) } } },
      "/api/v1/policy-watch": { get: { operationId: "getPolicyEvidenceWatch", tags: ["Products", "Intelligence"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/policy-watch/check": { post: { operationId: "checkPolicyEvidenceWatch", tags: ["Products", "Intelligence"], requestBody: { required: true, content: { "application/json": { schema: policyWatchCheckSchema } } }, responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/operations/policy-watch": { get: { operationId: "getPolicyEvidenceWatchOperations", tags: ["Observatory"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/evidence-dossier": { post: { operationId: "buildEvidenceDossier", tags: ["Products", "Intelligence"], requestBody: { required: true, content: { "application/json": { schema: evidenceDossierSchema } } }, responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/national-brief": { get: { operationId: "getNationalEvidenceBrief", tags: ["Products", "Intelligence"], parameters: [parameter("health_limit", false, { type: "integer", minimum: 1, maximum: 50, default: 12 }), parameter("industry_limit", false, { type: "integer", minimum: 1, maximum: 100, default: 50 }), parameter("emirate"), parameter("q", false, { type: "string", maxLength: 100 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/connectivity": { get: { operationId: "getConnectivityPulse", tags: ["Products", "Intelligence"], parameters: [parameter("series", false, { type: "string", enum: ["active_mobile_subscriptions", "broadband_per_100_inhabitants", "fixed_lines_per_100_inhabitants"] }), parameter("from", false, { type: "string", format: "date", description: "Inclusive month boundary in YYYY-MM-DD format." }), parameter("to", false, { type: "string", format: "date", description: "Inclusive month boundary in YYYY-MM-DD format." })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })), "422": response({ type: "object", additionalProperties: true }) } } },
      "/api/v1/tourism-pulse": { get: { operationId: "getTourismPulse", tags: ["Products", "Intelligence"], description: "Five separate official national annual hotel-sector series. Source-native units remain separate; descriptive trends do not establish causality.", parameters: [parameter("metric", false, { type: "string", enum: ["hotel_guest_arrivals", "guest_nights", "hotel_establishments", "hotel_rooms", "occupancy_rate"] }), parameter("from_year", false, { type: "integer", minimum: 2014, maximum: 2025 }), parameter("to_year", false, { type: "integer", minimum: 2014, maximum: 2025 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })), "422": response({ type: "object", additionalProperties: true }) } } },
      "/api/v1/places": { get: { operationId: "searchPlaceNames", tags: ["Products", "Maps"], parameters: [parameter("q", true, { type: "string", minLength: 2, maxLength: 100 }), parameter("limit", false, { type: "integer", minimum: 1, maximum: 100, default: 20 })], responses: { "200": response(envelope({ $ref: "#/components/schemas/PlaceNamesProduct" })) } } },
      "/api/v1/founder-pathway": { post: { operationId: "buildFounderPathway", tags: ["Products"], requestBody: { required: true, content: { "application/json": { schema: founderPathwaySchema } } }, responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/golden-residency": { get: { operationId: "getGoldenResidencyPathways", tags: ["Intelligence"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/golden-residency/assess": { post: { operationId: "assessGoldenResidencyReadiness", tags: ["Intelligence"], requestBody: { required: true, content: { "application/json": { schema: goldenAssessmentSchema } } }, responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/business-setup": { get: { operationId: "getBusinessSetupCatalogue", tags: ["Products"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/business-setup/route": { post: { operationId: "routeBusinessSetup", tags: ["Products"], requestBody: { required: true, content: { "application/json": { schema: businessSetupRouteSchema } } }, responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/startup-support": { get: { operationId: "getStartupSupportCatalogue", tags: ["Products"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/startup-support/match": { post: { operationId: "matchStartupSupport", tags: ["Products"], requestBody: { required: true, content: { "application/json": { schema: startupSupportMatchSchema } } }, responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/education": { get: { operationId: "getEducationLedger", tags: ["Intelligence"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/health-indicators": { get: { operationId: "getHealthIndicators", tags: ["Intelligence"], parameters: [parameter("q"), parameter("limit", false, { type: "integer", minimum: 1, maximum: 200 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/health-facilities": { get: { operationId: "getHealthFacilitiesAtlas", tags: ["Products", "Intelligence"], parameters: [parameter("year", false, { type: "integer", minimum: 2015, maximum: 2024, default: 2024 }), parameter("emirate"), parameter("sector", false, { type: "string", enum: ["Government", "Private"] }), parameter("category"), parameter("facility_type"), parameter("q", false, { type: "string", maxLength: 100 }), parameter("limit", false, { type: "integer", minimum: 1, maximum: 200, default: 100 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/health-facilities-map": { get: { operationId: "getHealthFacilitiesMap", tags: ["Products", "Intelligence", "Maps"], parameters: [parameter("q", false, { type: "string", minLength: 2, maxLength: 100 }), parameter("bbox", false, { type: "string", description: "min_lon,min_lat,max_lon,max_lat within UAE map bounds; mutually exclusive with near." }), parameter("near", false, { type: "string", description: "lat,lon,radius_km within UAE map bounds; radius is greater than 0 and at most 200 km; mutually exclusive with bbox." }), parameter("limit", false, { type: "integer", minimum: 1, maximum: 200, default: 100 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })), "422": response({ type: "object", additionalProperties: true }) } } },
      "/api/v1/aeronautical-publications": { get: { operationId: "getAeronauticalPublications", tags: ["Products", "Intelligence"], description: "Discovery-only GCAA eAIP publication index. Not NOTAM or operational flight guidance.", parameters: [parameter("kind", false, { type: "string", enum: ["airac_amendment", "supplement", "other"] }), parameter("limit", false, { type: "integer", minimum: 1, maximum: 50, default: 25 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })), "422": response({ type: "object", additionalProperties: true }) } } },
      "/api/v1/coverage": { get: { operationId: "getCoverage", tags: ["Catalog"], responses: { "200": response(envelope({ $ref: "#/components/schemas/Coverage" })) } } },
      "/api/v1/industry-atlas": { get: { operationId: "getIndustryAtlas", tags: ["Intelligence"], parameters: [parameter("emirate"), parameter("q"), parameter("limit", false, { type: "integer", minimum: 1, maximum: 1000 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/industry-atlas/change": { get: { operationId: "getIndustryChange", tags: ["Intelligence"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/trade-flow": { get: { operationId: "getTradeFlowRadar", tags: ["Intelligence"], parameters: [parameter("limit", false, { type: "integer", minimum: 1, maximum: 1000 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/ajman-business": { get: { operationId: "getAjmanBusinessEvidence", tags: ["Products", "Intelligence"], parameters: [parameter("q", false, { type: "string", maxLength: 100 }), parameter("limit", false, { type: "integer", minimum: 1, maximum: 1000, default: 500 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/ajman-urban": { get: { operationId: "getAjmanUrbanEvidence", tags: ["Products", "Intelligence"], parameters: [parameter("limit", false, { type: "integer", minimum: 1, maximum: 100, default: 100 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/ajman-parks": { get: { operationId: "getAjmanParksFootfall", tags: ["Products", "Intelligence"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/tax-services": { get: { operationId: "getTaxServiceActivity2025", tags: ["Intelligence"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/tax-services/archive": { get: { operationId: "getTaxServiceArchive", tags: ["Intelligence"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/sources": { get: { operationId: "listSources", tags: ["Catalog"], responses: { "200": response(envelope({ type: "array", items: { $ref: "#/components/schemas/Source" } })) } } },
      "/api/v1/search": { get: { operationId: "search", tags: ["Catalog"], parameters: [parameter("q", true), parameter("limit", false, { type: "integer", minimum: 1, maximum: 100 }), parameter("deep", false, { type: "boolean" })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/sources/{sourceId}/records": { get: { operationId: "getRecords", tags: ["Data"], parameters: [sourceId, parameter("dataset"), parameter("query"), parameter("limit", false, { type: "integer", minimum: 1, maximum: 1000 }), parameter("offset", false, { type: "integer", minimum: 0 })], responses: { "200": response(envelope({ type: "array", items: { type: "object", additionalProperties: true } })) } } },
      "/api/v1/sources/{sourceId}/schema": { get: { operationId: "getDatasetSchema", tags: ["Data"], parameters: [sourceId, parameter("dataset"), parameter("sample_size", false, { type: "integer", minimum: 1, maximum: 100 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/intelligence/recipes": { get: { operationId: "listRecipes", tags: ["Intelligence"], responses: { "200": response(envelope({ type: "array", items: { type: "object", additionalProperties: true } })) } } },
      "/api/v1/intelligence/indicators": { get: { operationId: "listIndicators", tags: ["Intelligence"], responses: { "200": response(envelope({ type: "array", items: { type: "object", additionalProperties: true } })) } } },
      "/api/v1/intelligence/indicators/{indicatorId}": { get: { operationId: "getIndicator", tags: ["Intelligence"], parameters: [{ name: "indicatorId", in: "path", required: true, schema: { type: "string" } }, parameter("source_id"), parameter("dataset")], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/observatory": { get: { operationId: "getObservatoryReport", tags: ["Observatory"], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/observatory/incidents": { get: { operationId: "listObservatoryIncidents", tags: ["Observatory"], parameters: [parameter("source_id"), parameter("limit", false, { type: "integer", minimum: 1, maximum: 500 })], responses: { "200": response(envelope({ type: "array", items: { type: "object", additionalProperties: true } })) } } },
      "/api/v1/observatory/sources/{sourceId}": { get: { operationId: "getObservatorySource", tags: ["Observatory"], parameters: [sourceId, parameter("limit", false, { type: "integer", minimum: 1, maximum: 500 })], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
      "/api/v1/sources/{sourceId}/tilejson": { get: { operationId: "getTileJson", tags: ["Maps"], parameters: [sourceId, parameter("dataset")], responses: { "200": response({ type: "object", additionalProperties: true }) } } },
      "/api/v1/spatial/join": { get: { operationId: "spatialJoin", tags: ["Maps"], parameters: [parameter("left_source", true), parameter("right_source", true), parameter("radius_km", false, { type: "number", exclusiveMinimum: 0, maximum: 500 })], responses: { "200": response(envelope({ type: "array", items: { type: "object", additionalProperties: true } })) } } },
      "/api/v1/entities/resolve": { get: { operationId: "resolveEntities", tags: ["Intelligence"], parameters: [parameter("left_source", true), parameter("right_source", true), parameter("left_fields", true), parameter("right_fields", true)], responses: { "200": response(envelope({ type: "object", additionalProperties: true })) } } },
    },
    components: { schemas: {
      Coverage: { type: "object", required: ["officialPortalsIndexed", "liveRecordConnectors"], properties: { officialPortalsIndexed: { type: "integer" }, liveRecordConnectors: { type: "integer" }, blockedConnectors: { type: "integer" }, keyRequiredPortals: { type: "integer" }, metadataOnlyPortals: { type: "integer" }, queryableDatasetsKnownMinimum: { type: "integer" } } },
      Source: { type: "object", required: ["id", "name_en", "name_ar", "kind", "access_status"], properties: { id: { type: "string" }, name_en: { type: "string" }, name_ar: { type: "string" }, owner: { type: "string" }, kind: { type: "string" }, access_status: { enum: ["live", "blocked", "key_required", "metadata_only"] }, base_url: { type: "string", format: "uri" } } },
      Product: { type: "object", required: ["id", "status", "access", "title", "description", "webPath", "apiPath", "sourceIds", "evidence"], properties: { id: { type: "string" }, status: { const: "published" }, access: { const: "public" }, category: { type: "string" }, title: { type: "object", additionalProperties: { type: "string" } }, description: { type: "object", additionalProperties: { type: "string" } }, webPath: { type: "string" }, apiPath: { type: "string" }, sourceIds: { type: "array", items: { type: "string" } }, evidence: { type: "object", additionalProperties: true } } },
      ToolCatalog: { type: "object", required: ["schemaVersion", "serverVersion", "generatedFrom", "summary", "tools"], properties: { schemaVersion: { type: "string" }, serverVersion: { type: "string" }, generatedFrom: { const: "runtime_registered_tools" }, summary: { type: "object", required: ["total", "read", "write", "mixed"], properties: { total: { type: "integer" }, read: { type: "integer" }, write: { type: "integer" }, mixed: { type: "integer" } } }, tools: { type: "array", items: { type: "object", required: ["name", "kind", "description"], properties: { name: { type: "string" }, kind: { enum: ["read", "write", "mixed"] }, description: { type: "string" } } } } } },
      PlaceNamesProduct: { type: "object", required: ["query", "returned", "mapped", "places", "evidence", "limitations", "lineage"], properties: { query: { type: "string" }, returned: { type: "integer" }, mapped: { type: "integer" }, places: { type: "array", items: { type: "object", additionalProperties: true } }, evidence: { type: "object", additionalProperties: true }, limitations: { type: "object", additionalProperties: true }, lineage: { type: "array", items: { type: "object", additionalProperties: true } } } },
    } },
  };
}
