type Localized = Readonly<{ en: string; ar: string }>;
export const STARTUP_STAGES = ["idea", "mvp", "early_revenue", "growth"] as const;
export const STARTUP_SUPPORT_TYPES = ["mentorship", "incubation", "market_access", "financing", "workspace"] as const;
export const STARTUP_EMIRATES = ["any", "abu_dhabi", "dubai", "sharjah", "ajman"] as const;
export type StartupStage = typeof STARTUP_STAGES[number];
export type StartupSupportType = typeof STARTUP_SUPPORT_TYPES[number];
export type StartupEmirate = typeof STARTUP_EMIRATES[number];
export type StartupSupportInput = Readonly<{ stage: StartupStage; supportType: StartupSupportType; emirate: StartupEmirate }>;

type Program = Readonly<{
  id: string; name: Localized; operator: Localized; scope: "federal" | Exclude<StartupEmirate, "any">;
  stages: readonly StartupStage[]; support: readonly StartupSupportType[]; officialUrl: string;
  summary: Localized; eligibilityNotes: readonly Localized[]; evidence: Localized;
}>;

const programs: readonly Program[] = Object.freeze([
  { id: "mbrif_accelerator", name: { en: "MBRIF Accelerator", ar: "مسرّع صندوق محمد بن راشد للابتكار" }, operator: { en: "Mohammed Bin Rashid Innovation Fund", ar: "صندوق محمد بن راشد للابتكار" }, scope: "federal", stages: ["idea", "mvp", "early_revenue", "growth"], support: ["mentorship", "incubation", "market_access"], officialUrl: "https://mbrif.ae/program-selection-2/", summary: { en: "Zero-fee, non-dilutive tailored innovation support and expert access.", ar: "دعم ابتكار مخصص دون رسوم أو تخفيف للملكية مع الوصول إلى خبراء." }, eligibilityNotes: [{ en: "Innovation fit and programme selection are assessed by MBRIF.", ar: "يقيّم الصندوق ملاءمة الابتكار والاختيار للبرنامج." }], evidence: { en: "Official MBRIF programme selection page.", ar: "صفحة اختيار البرامج الرسمية للصندوق." } },
  { id: "mbrif_guarantee", name: { en: "MBRIF Guarantee Scheme", ar: "برنامج ضمان التمويل للصندوق" }, operator: { en: "Mohammed Bin Rashid Innovation Fund", ar: "صندوق محمد بن راشد للابتكار" }, scope: "federal", stages: ["early_revenue", "growth"], support: ["financing"], officialUrl: "https://mbrif.ae/program-selection-2/", summary: { en: "Government-backed credit guarantees for qualifying innovative companies.", ar: "ضمانات ائتمانية حكومية للشركات الابتكارية المؤهلة." }, eligibilityNotes: [{ en: "This is a credit guarantee, not a grant or automatic loan approval.", ar: "هذا ضمان ائتماني وليس منحة أو موافقة تمويل تلقائية." }], evidence: { en: "Official MBRIF programme selection page.", ar: "صفحة اختيار البرامج الرسمية للصندوق." } },
  { id: "edb_startup_finance", name: { en: "EDB Startup Financing", ar: "تمويل الشركات الناشئة من مصرف الإمارات للتنمية" }, operator: { en: "Emirates Development Bank", ar: "مصرف الإمارات للتنمية" }, scope: "federal", stages: ["early_revenue", "growth"], support: ["financing", "mentorship"], officialUrl: "https://www.edb.gov.ae/en/customers/startups", summary: { en: "Startup finance and Business Lab support focused on national priority sectors.", ar: "تمويل للشركات الناشئة ودعم مختبر الأعمال مع تركيز على القطاعات الوطنية ذات الأولوية." }, eligibilityNotes: [{ en: "Financing is subject to EDB financial, qualitative, sector and documentation assessment.", ar: "التمويل خاضع للتقييم المالي والنوعي والقطاعي والمستندي للمصرف." }], evidence: { en: "Official EDB startup solutions page.", ar: "صفحة حلول الشركات الناشئة الرسمية للمصرف." } },
  { id: "hub71_initiate", name: { en: "Hub71 Initiate", ar: "برنامج Initiate من Hub71" }, operator: { en: "Hub71", ar: "Hub71" }, scope: "abu_dhabi", stages: ["idea", "mvp"], support: ["incubation", "mentorship", "workspace", "market_access"], officialUrl: "https://www.hub71.com/program/initiate", summary: { en: "Venture-builder support for ideation and pre-MVP founders building from Abu Dhabi.", ar: "دعم عبر بناة المشاريع للمؤسسين في مرحلة الفكرة وما قبل النموذج الأولي من أبوظبي." }, eligibilityNotes: [{ en: "Venture builders set selection and any equity terms; Hub71 does not provide direct funding through Initiate.", ar: "يحدد بناة المشاريع شروط الاختيار والملكية؛ ولا يقدم Hub71 تمويلًا مباشرًا عبر Initiate." }], evidence: { en: "Official Hub71 Initiate programme page.", ar: "صفحة برنامج Initiate الرسمية." } },
  { id: "hub71_access", name: { en: "Hub71 Access", ar: "برنامج Access من Hub71" }, operator: { en: "Hub71", ar: "Hub71" }, scope: "abu_dhabi", stages: ["mvp", "early_revenue", "growth"], support: ["market_access", "mentorship", "workspace", "financing"], officialUrl: "https://www.hub71.com/program/access-programme", summary: { en: "A structured Abu Dhabi ecosystem programme for pre-seed to Series A startups.", ar: "برنامج منظومة منظم في أبوظبي للشركات من ما قبل البذرة حتى الجولة A." }, eligibilityNotes: [{ en: "Incentives, equity and acceptance depend on the current programme terms and selection.", ar: "تعتمد الحوافز والملكية والقبول على شروط البرنامج الحالية والاختيار." }], evidence: { en: "Official Hub71 Access programme page.", ar: "صفحة برنامج Access الرسمية." } },
  { id: "dubai_sme", name: { en: "Dubai SME founder support", ar: "دعم المؤسسين من دبي للمشاريع الصغيرة والمتوسطة" }, operator: { en: "Mohammed Bin Rashid Establishment for SME Development", ar: "مؤسسة محمد بن راشد لتنمية المشاريع الصغيرة والمتوسطة" }, scope: "dubai", stages: ["idea", "mvp", "early_revenue", "growth"], support: ["mentorship", "incubation", "market_access", "workspace", "financing"], officialUrl: "https://sme.ae/faq/en", summary: { en: "Guidance, training, incubator, procurement and selected finance services.", ar: "توجيه وتدريب وحاضنات ومشتريات وخدمات تمويل مختارة." }, eligibilityNotes: [{ en: "Many benefits are limited to UAE or GCC nationals and programme-specific conditions.", ar: "تقتصر مزايا كثيرة على مواطني الإمارات أو دول المجلس وشروط كل برنامج." }], evidence: { en: "Official Dubai SME service FAQ.", ar: "الأسئلة الرسمية لخدمات دبي للمشاريع الصغيرة والمتوسطة." } },
  { id: "sheraa_s3", name: { en: "Sharjah Startup Studio (S3)", ar: "استوديو الشارقة للشركات الناشئة (S3)" }, operator: { en: "Sharjah Entrepreneurship Center", ar: "مركز الشارقة لريادة الأعمال" }, scope: "sharjah", stages: ["mvp", "early_revenue", "growth"], support: ["incubation", "mentorship", "market_access", "workspace"], officialUrl: "https://www.startups.sheraa.ae/", summary: { en: "Founder-first scaling support, expert access and Sharjah ecosystem connections.", ar: "دعم للنمو يركز على المؤسس مع خبراء وروابط بمنظومة الشارقة." }, eligibilityNotes: [{ en: "Programme cohorts, target sectors, licensing commitments and application windows change.", ar: "تتغير الدفعات والقطاعات المستهدفة والتزامات الترخيص وفترات التقديم." }], evidence: { en: "Official Sheraa S3 programme page.", ar: "صفحة برنامج S3 الرسمية لشراع." } },
  { id: "ruwad_financing", name: { en: "Ruwad Financing Programme", ar: "برنامج تمويل رواد" }, operator: { en: "Sharjah Entrepreneurship Foundation — Ruwad", ar: "مؤسسة الشارقة لدعم المشاريع الريادية – رواد" }, scope: "sharjah", stages: ["mvp", "early_revenue", "growth"], support: ["financing", "mentorship"], officialUrl: "https://ruwad.ae/en/financing-program", summary: { en: "Direct and indirect financing support for qualifying national projects in Sharjah.", ar: "دعم تمويل مباشر وغير مباشر للمشروعات الوطنية المؤهلة في الشارقة." }, eligibilityNotes: [{ en: "National-project and programme eligibility restrictions apply.", ar: "تطبق قيود أهلية المشروعات الوطنية وشروط البرنامج." }], evidence: { en: "Official Ruwad financing programme page.", ar: "صفحة برنامج التمويل الرسمية لرواد." } },
  { id: "ajman_reyada", name: { en: "Ajman Reyada Programme", ar: "برنامج ريادة – عجمان" }, operator: { en: "Ajman Department of Economic Development", ar: "دائرة التنمية الاقتصادية – عجمان" }, scope: "ajman", stages: ["idea", "mvp", "early_revenue"], support: ["mentorship", "market_access"], officialUrl: "https://www.ajmanded.ae/en/why-ajman/sme-programs/reyada-program", summary: { en: "Ajman programme supporting eligible Emirati home and small business projects.", ar: "برنامج في عجمان لدعم المشروعات المنزلية والصغيرة الإماراتية المؤهلة." }, eligibilityNotes: [{ en: "The published programme is targeted to eligible UAE nationals and local conditions.", ar: "البرنامج المنشور موجه للمواطنين الإماراتيين المؤهلين وشروط محلية." }], evidence: { en: "Official Ajman DED Reyada page.", ar: "صفحة برنامج ريادة الرسمية لدائرة عجمان." } },
]);

export function startupSupportCatalogue() {
  return { kind: "uae_startup_support_catalogue" as const, verifiedAt: "2026-07-17" as const, programs: programs.map((program) => ({ ...program, name: { ...program.name }, operator: { ...program.operator }, stages: [...program.stages], support: [...program.support], summary: { ...program.summary }, eligibilityNotes: program.eligibilityNotes.map((note) => ({ ...note })), evidence: { ...program.evidence } })), disclaimer: { en: "Discovery only. Programme availability, application windows and eligibility can change; verify on the official page before applying.", ar: "للاكتشاف فقط. قد تتغير إتاحة البرامج وفترات التقديم والأهلية؛ تحقق من الصفحة الرسمية قبل التقديم." } };
}

export function matchStartupSupport(input: StartupSupportInput) {
  const ranked = programs.map((program) => {
    const stage = program.stages.includes(input.stage);
    const support = program.support.includes(input.supportType);
    const location = input.emirate === "any" || program.scope === "federal" || program.scope === input.emirate;
    const relevance = (stage ? 4 : 0) + (support ? 5 : 0) + (location ? 3 : 0);
    const reasons: Localized[] = [];
    if (stage) reasons.push({ en: `Published for ${input.stage.replaceAll("_", " ")} stage support.`, ar: `منشور لدعم مرحلة ${input.stage}.` });
    if (support) reasons.push({ en: `Includes ${input.supportType.replaceAll("_", " ")} support.`, ar: `يتضمن دعم ${input.supportType}.` });
    if (location) reasons.push({ en: program.scope === "federal" ? "Federal UAE scope." : `Relevant to ${program.scope.replaceAll("_", " ")}.`, ar: program.scope === "federal" ? "نطاق اتحادي في الإمارات." : `مرتبط بإمارة ${program.scope}.` });
    return { program, relevance, reasons };
  }).filter((item) => item.relevance >= 8).sort((a, b) => b.relevance - a.relevance || a.program.id.localeCompare(b.program.id)).slice(0, 6);
  return {
    kind: "uae_startup_support_matches" as const, decision: "discovery_only" as const, stored: false, input: { ...input },
    matches: ranked.map(({ program, relevance, reasons }) => ({ programId: program.id, name: { ...program.name }, operator: { ...program.operator }, scope: program.scope, officialUrl: program.officialUrl, relevance, reasons, summary: { ...program.summary }, eligibilityNotes: program.eligibilityNotes.map((note) => ({ ...note })), eligibilityDetermined: false as const })),
    caveats: [{ en: "Relevance is not eligibility, acceptance, funding approval or a recommendation to take debt or give equity.", ar: "الملاءمة ليست أهلية أو قبولًا أو موافقة تمويل أو توصية بالاقتراض أو التنازل عن ملكية." }, { en: "Open the official page to confirm the current cohort, deadline, terms and required evidence.", ar: "افتح الصفحة الرسمية للتحقق من الدفعة الحالية والموعد والشروط والأدلة المطلوبة." }],
  };
}
