export type ToolKind = "read" | "write" | "mixed";
export interface ToolCatalogEntry { name: string; kind: ToolKind; description: string }

export function createToolCatalog(registeredTools: Record<string, { description?: string }>, version: string) {
  const tools = Object.entries(registeredTools).map(([name, definition]): ToolCatalogEntry => {
    const description = definition.description?.trim() ?? "";
    const kind: ToolKind = name === "uae_dataset_snapshot" ? "mixed" : description.startsWith("[WRITE") || name === "uae_source_add" || name === "uae_source_add_metadata" ? "write" : "read";
    return { name, kind, description };
  }).sort((a, b) => a.name.localeCompare(b.name));
  return {
    schemaVersion: "1.0",
    serverVersion: version,
    generatedFrom: "runtime_registered_tools",
    summary: { total: tools.length, read: tools.filter((tool) => tool.kind === "read").length, write: tools.filter((tool) => tool.kind === "write").length, mixed: tools.filter((tool) => tool.kind === "mixed").length },
    tools,
  } as const;
}

export function toolCatalogMarkdown(catalog: ReturnType<typeof createToolCatalog>): string {
  const rows = catalog.tools.map((tool) => `| \`${tool.name}\` | ${tool.kind} | ${tool.description.replaceAll("|", "\\|")} |`).join("\n");
  return `<!-- Generated by bun run generate:tools. Do not edit. -->
# MCP tool catalog

Runtime contract for Open Emirates Intelligence v${catalog.serverVersion}.

| Tool | Kind | Runtime description |
| --- | --- | --- |
${rows}

Total: ${catalog.summary.total} tools — ${catalog.summary.read} read, ${catalog.summary.write} write, ${catalog.summary.mixed} mixed.
`;
}
