export function landingPage(): string {
  return `<!doctype html>
<html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Open Emirates Intelligence — official UAE open data, made queryable for people, applications and AI agents.">
<meta name="theme-color" content="#173d2d"><title>Open Emirates Intelligence — The Emirates, queryable.</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Manrope:wght@400;500;600;700&family=Noto+Kufi+Arabic:wght@400;500;600;700&display=swap');
:root{--ivory:#f1eddf;--paper:#e8e1ce;--ink:#13251d;--forest:#173d2d;--green:#087443;--red:#c34032;--gold:#bf9a55;--muted:#66736b;--line:rgba(19,37,29,.25);--night:#0d1914;--ease:cubic-bezier(.22,1,.36,1)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--ivory);color:var(--ink);font-family:Manrope,"Noto Kufi Arabic",sans-serif;overflow-x:hidden}a{color:inherit}button,input,select,code,pre,.mono{font-family:"IBM Plex Mono",monospace}.shell{max-width:1600px;margin:auto;border-inline:1px solid var(--line);min-height:100vh}.top{height:76px;border-bottom:1px solid var(--ink);display:flex;align-items:center;justify-content:space-between;padding:0 clamp(18px,3vw,46px);position:sticky;top:0;background:rgba(241,237,223,.94);backdrop-filter:blur(12px);z-index:20}.identity{display:flex;align-items:center;gap:13px;text-decoration:none}.mark{width:34px;height:34px}.wordmark{font-size:12px;font-weight:700;letter-spacing:.12em;line-height:1.25}.wordmark small{display:block;color:var(--muted);font:8px/1.4 "IBM Plex Mono";letter-spacing:.14em}.nav{display:flex;align-items:center;gap:24px}.nav a{text-decoration:none;font:10px "IBM Plex Mono";letter-spacing:.07em}.nav a:hover{color:var(--red)}.lang,.button{border:1px solid var(--ink);border-radius:0;padding:12px 16px;background:var(--ink);color:var(--ivory);font:10px "IBM Plex Mono";letter-spacing:.06em;cursor:pointer;text-decoration:none;transition:transform .3s var(--ease),background .3s,color .3s}.lang,.button.alt{background:transparent;color:var(--ink)}.button:hover,.lang:hover{transform:translateY(-2px);background:var(--red);border-color:var(--red);color:var(--ivory)}
.ticker{height:34px;background:var(--forest);color:#e6ddc6;display:flex;align-items:center;overflow:hidden;border-bottom:1px solid var(--ink);font:9px "IBM Plex Mono";letter-spacing:.1em}.ticker-track{display:flex;gap:54px;white-space:nowrap;animation:ticker 28s linear infinite}.ticker-track span:before{content:'◆';color:var(--gold);margin-inline-end:54px}@keyframes ticker{to{transform:translateX(-50%)}}
.hero{display:grid;grid-template-columns:minmax(0,1.12fr) minmax(420px,.88fr);min-height:720px;border-bottom:1px solid var(--ink)}.hero-copy{padding:clamp(68px,8vw,126px) clamp(24px,6vw,92px);position:relative}.edition{display:flex;align-items:center;gap:12px;font:9px "IBM Plex Mono";letter-spacing:.14em;color:var(--green)}.edition:before{content:'';width:36px;height:1px;background:var(--green)}h1{font-size:clamp(66px,8.3vw,132px);line-height:.79;letter-spacing:-.075em;margin:58px 0 42px;max-width:900px;font-weight:600}h1 em{font-style:normal;color:var(--red)}.lede{font-size:clamp(16px,1.55vw,23px);line-height:1.55;max-width:680px;color:#44534b}.actions{display:flex;gap:10px;margin-top:34px;flex-wrap:wrap}.install{display:flex;align-items:center;gap:10px;margin-top:42px;font:10px "IBM Plex Mono";color:var(--muted)}.install code{padding:10px 13px;border:1px solid var(--line);background:rgba(255,255,255,.2);color:var(--ink)}
.hero-visual{position:relative;background:var(--forest);color:var(--ivory);overflow:hidden;border-inline-start:1px solid var(--ink);min-height:600px}.map-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(232,225,206,.09) 1px,transparent 1px),linear-gradient(90deg,rgba(232,225,206,.09) 1px,transparent 1px);background-size:48px 48px}.orbit{position:absolute;border:1px solid rgba(232,225,206,.21);border-radius:50%;animation:spin 36s linear infinite}.orbit.o1{width:520px;height:520px;left:50%;top:46%;transform:translate(-50%,-50%)}.orbit.o2{width:350px;height:350px;left:50%;top:46%;transform:translate(-50%,-50%);animation-direction:reverse;animation-duration:22s}.orbit:after{content:'';width:8px;height:8px;background:var(--red);position:absolute;left:50%;top:-4px;transform:rotate(45deg)}@keyframes spin{to{rotate:360deg}}.uae-map{position:absolute;width:82%;left:9%;top:20%;filter:drop-shadow(0 30px 40px rgba(0,0,0,.22))}.uae-map path{fill:#d8ca9e;stroke:var(--night);stroke-width:1.5;transform-origin:center;animation:mapPulse 6s var(--ease) infinite}.uae-map path:nth-child(2n){animation-delay:-2s}.uae-map path:nth-child(3n){animation-delay:-4s}@keyframes mapPulse{0%,100%{fill:#d8ca9e}50%{fill:#c8b77e}}.pulse{animation:pulse 2.4s ease-out infinite;transform-origin:center}@keyframes pulse{0%{r:4;opacity:1}100%{r:24;opacity:0}}.visual-label{position:absolute;inset-inline:28px;top:26px;display:flex;justify-content:space-between;font:9px "IBM Plex Mono";letter-spacing:.1em}.visual-label span:last-child{color:#99b5a5}.visual-foot{position:absolute;inset-inline:28px;bottom:27px;display:flex;justify-content:space-between;align-items:end}.visual-foot strong{font-size:clamp(34px,5vw,70px);line-height:.86;letter-spacing:-.05em}.visual-foot span{font:9px/1.6 "IBM Plex Mono";text-align:end;color:#a8b6ad}.coordinates{position:absolute;right:22px;top:50%;writing-mode:vertical-rl;font:8px "IBM Plex Mono";letter-spacing:.14em;color:#93a79b}
.proof{display:grid;grid-template-columns:1.5fr repeat(4,1fr);border-bottom:1px solid var(--ink)}.proof-intro,.stat{padding:25px clamp(16px,2.5vw,34px);min-height:132px;border-inline-end:1px solid var(--line);display:flex;flex-direction:column;justify-content:space-between}.proof-intro{background:var(--red);color:var(--ivory)}.proof-intro b{font-size:18px}.proof-intro span,.stat span{font:9px/1.5 "IBM Plex Mono";letter-spacing:.08em;text-transform:uppercase}.stat strong{font:clamp(31px,3vw,47px) "IBM Plex Mono";font-weight:400}.stat small{color:var(--muted)}
.section{padding:clamp(70px,9vw,132px) clamp(20px,5vw,76px);border-bottom:1px solid var(--ink)}.section-head{display:grid;grid-template-columns:.7fr 1.3fr;gap:40px;align-items:end;margin-bottom:60px}.eyebrow{font:9px "IBM Plex Mono";letter-spacing:.15em;color:var(--red)}.section h2{font-size:clamp(44px,6.2vw,94px);line-height:.92;letter-spacing:-.06em;margin:0;font-weight:600}.section-head p{max-width:590px;color:var(--muted);line-height:1.65;margin:0 0 6px}.flow{display:grid;grid-template-columns:repeat(5,1fr);border-top:1px solid var(--ink);border-inline-start:1px solid var(--ink)}.step{min-height:240px;padding:24px;border-inline-end:1px solid var(--ink);border-bottom:1px solid var(--ink);position:relative;transition:background .35s,color .35s}.step:hover{background:var(--forest);color:var(--ivory)}.step b{font:10px "IBM Plex Mono";color:var(--red)}.step h3{font-size:22px;margin:74px 0 12px}.step p{font-size:13px;line-height:1.55;color:var(--muted)}.step:hover p{color:#a9b7ae}.step:not(:last-child):after{content:'↗';position:absolute;right:16px;top:19px;font-size:20px}
.dark{background:var(--night);color:var(--ivory)}.dark .section-head p{color:#9fafa5}.dark .eyebrow{color:#d8b86f}.signal-layout{display:grid;grid-template-columns:.82fr 1.18fr;border:1px solid #405148}.signal-copy{padding:clamp(28px,5vw,70px);border-inline-end:1px solid #405148}.signal-copy blockquote{font-size:clamp(29px,4.4vw,65px);line-height:1.08;letter-spacing:-.05em;margin:0 0 80px}.signal-copy blockquote em{color:#d8b86f;font-style:normal}.signal-list{list-style:none;padding:0;margin:0}.signal-list li{border-top:1px solid #405148;padding:15px 0;display:flex;justify-content:space-between;font:10px "IBM Plex Mono"}.signal-list span{color:#8da096}.terminal{padding:24px;background:#101e18;min-width:0}.terminal-top{display:flex;justify-content:space-between;border-bottom:1px solid #405148;padding-bottom:14px;font:9px "IBM Plex Mono";color:#98a99f}.terminal pre{white-space:pre-wrap;font:clamp(10px,1.1vw,13px)/1.8 "IBM Plex Mono";color:#d8dfda;margin:30px 0}.terminal .key{color:#d8b86f}.terminal .value{color:#7dc89f}.terminal .cursor{display:inline-block;width:7px;height:15px;background:var(--red);vertical-align:middle;animation:blink 1s steps(1) infinite}@keyframes blink{50%{opacity:0}}
.gallery{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--ink);border-inline-start:1px solid var(--ink)}.connector{padding:22px;border-inline-end:1px solid var(--ink);border-bottom:1px solid var(--ink);min-height:180px;transition:background .3s}.connector:hover{background:var(--paper)}.connector small{font:8px "IBM Plex Mono";color:var(--green)}.connector strong{display:block;font:18px "IBM Plex Mono";margin:54px 0 10px}.connector span{font-size:12px;color:var(--muted)}
.filters{display:grid;grid-template-columns:1fr 240px;gap:10px;margin-bottom:18px}.field{width:100%;background:transparent;border:1px solid var(--ink);padding:14px;color:var(--ink);font-size:12px;border-radius:0}.catalog{border-top:1px solid var(--ink)}.source{display:grid;grid-template-columns:64px minmax(220px,1.4fr) 1fr 120px 130px;gap:14px;padding:18px 8px;border-bottom:1px solid var(--line);align-items:center;transition:padding .25s,background .25s}.source:hover{background:var(--paper);padding-inline:15px}.source-title{font-weight:700}.source small{display:block;color:var(--muted);margin-top:4px}.tag,.status{font:9px "IBM Plex Mono";text-transform:uppercase}.status.live{color:var(--green)}.status.blocked{color:var(--red)}.empty{padding:34px 8px;color:var(--muted)}
.workbench,.dataset-browser{display:grid;grid-template-columns:.72fr 1.28fr;border:1px solid var(--ink);min-height:430px}.controls{padding:30px;border-inline-end:1px solid var(--ink)}label{display:block;font:9px "IBM Plex Mono";text-transform:uppercase;margin:20px 0 8px}.run{margin-top:22px}.output{background:var(--night);color:#dce7dc;padding:30px;overflow:auto;margin:0;font-size:11px;line-height:1.7;white-space:pre-wrap;max-height:560px}.notice{font:9px "IBM Plex Mono";color:var(--muted);margin-top:12px}.dataset-results{overflow:auto;max-height:520px}.dataset{padding:18px 22px;border-bottom:1px solid var(--line)}.dataset strong{display:block;font-size:14px}.dataset span{font:9px "IBM Plex Mono";color:var(--muted)}
.community{display:grid;grid-template-columns:1.15fr .85fr;background:var(--red);color:var(--ivory)}.community>div{padding:clamp(56px,8vw,110px);border-inline-end:1px solid rgba(241,237,223,.4)}.community h2{font-size:clamp(48px,7vw,105px);line-height:.88;letter-spacing:-.065em;margin:0 0 35px}.community p{max-width:570px;line-height:1.6}.community .button{border-color:var(--ivory);background:var(--ivory);color:var(--red)}.community .button.alt{background:transparent;color:var(--ivory)}.seal{display:flex;align-items:center;justify-content:center;min-height:420px}.seal svg{width:min(320px,70%);animation:spin 42s linear infinite}.footer{padding:30px clamp(18px,3vw,46px);display:flex;justify-content:space-between;font:9px "IBM Plex Mono";letter-spacing:.08em}.loading{opacity:.55}.reveal{opacity:0;transform:translateY(24px);transition:opacity .9s var(--ease),transform .9s var(--ease)}.reveal.visible{opacity:1;transform:none}
[dir=rtl] body{font-family:"Noto Kufi Arabic",Manrope,sans-serif}[dir=rtl] h1{letter-spacing:-.035em}[dir=rtl] .source{font-size:13px}
@media(max-width:1050px){.nav a{display:none}.hero{grid-template-columns:1fr}.hero-visual{border-inline-start:0;border-top:1px solid var(--ink);min-height:620px}.proof{grid-template-columns:repeat(2,1fr)}.proof-intro{grid-column:span 2}.flow{grid-template-columns:repeat(2,1fr)}.gallery{grid-template-columns:repeat(3,1fr)}.section-head{grid-template-columns:1fr}.signal-layout,.workbench,.dataset-browser{grid-template-columns:1fr}.signal-copy,.controls{border-inline-end:0;border-bottom:1px solid var(--ink)}.source{grid-template-columns:50px 1fr 110px}.source .owner,.source .connector{display:none}}
@media(max-width:650px){html,body{max-width:100%;overflow-x:hidden}.shell{width:100vw;max-width:100vw}.top{width:100vw;height:66px;padding-inline:16px}.identity{gap:9px}.mark{width:32px;height:32px}.wordmark{font-size:9px;letter-spacing:.08em}.wordmark small{display:none}.nav{gap:0}.lang{padding:10px 9px;font-size:9px}.hero{display:block;width:100vw}.hero-copy{width:100vw;padding:64px 22px 68px;min-width:0;overflow:hidden}h1{font-size:clamp(50px,14vw,60px);letter-spacing:-.06em;margin-block:50px 35px}.lede{width:100%;max-width:100%;font-size:15px;overflow-wrap:anywhere}.hero-visual{width:100vw;min-height:490px}.visual-label{inset-inline:28px;font-size:8px}.visual-label span:last-child{display:none}.visual-foot strong{font-size:38px}.proof{grid-template-columns:1fr 1fr}.proof-intro{grid-column:span 2}.section{padding-block:72px}.flow,.gallery{grid-template-columns:1fr}.filters{grid-template-columns:1fr}.source{grid-template-columns:35px 1fr}.source .status{display:none}.community{grid-template-columns:1fr}.community>div{border-inline-end:0}.seal{min-height:320px}.footer{display:block}.footer span{display:block;margin:6px 0}.install{display:none}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;scroll-behavior:auto!important}.reveal{opacity:1;transform:none}}
</style></head><body><div class="shell">
<header class="top"><a class="identity" href="/"><svg class="mark" viewBox="0 0 48 48" aria-hidden="true"><rect width="48" height="48" fill="#173d2d"/><path d="M9 32V18h4v14zm6 0V13h4v19zm6 0V20h4v12zm6 0V10h4v22zm6 0V16h4v16z" fill="#f1eddf"/><path d="M9 35h28" stroke="#c34032" stroke-width="3"/></svg><span class="wordmark">OPEN EMIRATES<small>INTELLIGENCE / ذكاء الإمارات المفتوح</small></span></a><nav class="nav"><a href="/tax-services">TAX ACTIVITY</a><a href="/observatory">OBSERVATORY</a><a href="/places">PLACE NAMES</a><a href="/industry-atlas">INDUSTRY ATLAS</a><a href="#system">SYSTEM</a><a href="#connectors">CONNECTORS</a><a href="#catalog">CATALOG</a><a href="#playground">PLAYGROUND</a><a href="/openapi.json">OPENAPI</a><button class="lang" id="lang">العربية</button></nav></header>
<div class="ticker"><div class="ticker-track"><span>OFFICIAL SOURCES</span><span>BILINGUAL SEMANTICS</span><span>SOURCE-CITED ANSWERS</span><span>OPEN MCP</span><span>BUILT ON BUN</span><span>OFFICIAL SOURCES</span><span>BILINGUAL SEMANTICS</span><span>SOURCE-CITED ANSWERS</span><span>OPEN MCP</span><span>BUILT ON BUN</span></div></div>
<main><section class="hero"><div class="hero-copy"><div class="edition" data-en="THE PUBLIC DATA LAYER / EDITION 01" data-ar="طبقة البيانات العامة / الإصدار ٠١">THE PUBLIC DATA LAYER / EDITION 01</div><h1 data-en="The Emirates,<br><em>queryable.</em>" data-ar="الإمارات،<br><em>قابلة للاستعلام.</em>">The Emirates,<br><em>queryable.</em></h1><p class="lede" data-en="Official UAE data, translated into one verifiable language for agents, researchers and builders. Every answer keeps its source." data-ar="بيانات الإمارات الرسمية بلغة واحدة قابلة للتحقق للمساعدات والباحثين والمطورين. كل إجابة تحتفظ بمصدرها.">Official UAE data, translated into one verifiable language for agents, researchers and builders. Every answer keeps its source.</p><div class="actions"><a class="button" href="#playground" data-en="EXPLORE LIVE DATA ↗" data-ar="استكشف البيانات الحية ↗">EXPLORE LIVE DATA ↗</a><a class="button alt" href="https://github.com/ahmedvnabil/Open-Emirates-Intelligence-MCP">VIEW SOURCE</a></div><div class="install"><span>CONNECT</span><code>https://uaemcp.zad.tools/mcp</code></div></div>
<div class="hero-visual" aria-label="Animated UAE data map"><div class="map-grid"></div><div class="orbit o1"></div><div class="orbit o2"></div><div class="visual-label"><span>FEDERATION DATA MAP / LIVE</span><span>24.4539° N — 54.3773° E</span></div><svg class="uae-map" viewBox="0 0 700 430" role="img"><path d="M78 218l51-44 72-18 51-50 91-12 55 31 49-14 61 30 88 18-33 44-74 23-77 46-111 3-63 36-76-20-48-37z"/><path d="M447 141l32-57 72-29 53 17-20 54-76 33z"/><path d="M129 174l-27-49 36-42 45 18 18 55z"/><path d="M201 156l11-61 40-29 35 29-35 11z"/><path d="M398 125l5-54 43-28 33 41-32 57z"/><path d="M508 159l25-47 51 14-2 41z"/><path d="M596 159l22-43 37 18-18 47z"/><g fill="#c34032"><circle cx="343" cy="192" r="5"/><circle class="pulse" cx="343" cy="192" r="5"/><circle cx="501" cy="156" r="5"/><circle class="pulse" cx="501" cy="156" r="5"/><circle cx="166" cy="201" r="5"/><circle class="pulse" cx="166" cy="201" r="5"/></g><g stroke="#c34032" stroke-width="1" fill="none" stroke-dasharray="5 7"><path d="M166 201Q280 120 343 192T501 156"/><path d="M343 192Q430 300 560 202"/></g></svg><div class="coordinates">DATA NEVER FABRICATED / PROVENANCE RETAINED</div><div class="visual-foot"><strong>07<br>EMIRATES</strong><span>ONE OPEN<br>INTELLIGENCE LAYER<br>VERSION 1.44</span></div></div></section>
<section class="proof"><div class="proof-intro"><b data-en="Trust is a feature." data-ar="الثقة جزء من المنتج.">Trust is a feature.</b><span>PROVENANCE / QUALITY / LINEAGE</span></div><div class="stat"><strong id="portals">—</strong><span>Official portals<br><small>indexed</small></span></div><div class="stat"><strong id="live">—</strong><span>Live connectors<br><small>queryable now</small></span></div><div class="stat"><strong>22</strong><span>Focused tools<br><small>MCP native</small></span></div><div class="stat"><strong>06</strong><span>Language SDKs<br><small>one contract</small></span></div></section>
<section class="section reveal" id="system"><div class="section-head"><div><div class="eyebrow">SYSTEM / 01</div><h2 data-en="Evidence,<br>end to end." data-ar="الدليل،<br>من البداية للنهاية.">Evidence,<br>end to end.</h2></div><p data-en="A public data route you can inspect. Every derived answer carries origin, transformation, limitations and citation. Unavailable data stays unavailable—never invented." data-ar="مسار بيانات عام يمكنك فحصه. كل نتيجة مشتقة تحمل المصدر والتحويلات والقيود والاستشهاد. البيانات غير المتاحة لا يتم اختلاقها.">A public data route you can inspect. Every derived answer carries origin, transformation, limitations and citation.</p></div><div class="flow"><article class="step"><b>01 / SOURCE</b><h3>Official portal</h3><p>Government APIs, catalogs and published files.</p></article><article class="step"><b>02 / ACCESS</b><h3>Safe connector</h3><p>SSRF-guarded, bounded and capability-aware.</p></article><article class="step"><b>03 / MEANING</b><h3>Semantic layer</h3><p>Arabic and English schemas, places and entities.</p></article><article class="step"><b>04 / EVIDENCE</b><h3>Intelligence</h3><p>Indicators, history, geo, recipes and lineage.</p></article><article class="step"><b>05 / DELIVERY</b><h3>Any client</h3><p>MCP, REST, vector maps and six SDKs.</p></article></div></section>
<section class="section dark reveal"><div class="section-head"><div><div class="eyebrow">MANIFEST / 02</div><h2 data-en="No black box." data-ar="لا صندوق أسود.">No black box.</h2></div><p>Results preserve the exact evidence an agent needs to explain where an answer came from—and what it cannot prove.</p></div><div class="signal-layout"><div class="signal-copy"><blockquote>Ask a country-sized question.<br><em>Keep the receipts.</em></blockquote><ul class="signal-list"><li>ORIGIN <span>OFFICIAL SOURCE</span></li><li>LICENSE <span>DATASET LEVEL</span></li><li>QUALITY <span>MEASURED</span></li><li>LINEAGE <span>REPLAYABLE</span></li></ul></div><div class="terminal"><div class="terminal-top"><span>OEI / LIVE RESPONSE</span><span>200 OK — 42MS</span></div><pre>{
  <span class="key">"ok"</span>: <span class="value">true</span>,
  <span class="key">"data"</span>: [{
    <span class="key">"emirate"</span>: <span class="value">"Abu Dhabi"</span>,
    <span class="key">"entity_type"</span>: <span class="value">"industrial_license"</span>
  }],
  <span class="key">"meta"</span>: {
    <span class="key">"source_id"</span>: <span class="value">"moiat_industrial_licenses"</span>,
    <span class="key">"citation"</span>: <span class="value">"official.gov.ae/..."</span>,
    <span class="key">"quality_score"</span>: <span class="value">0.94</span>,
    <span class="key">"fetched_at"</span>: <span class="value">"2026-07-17T04:28:12Z"</span>
  }
}

<span class="cursor"></span></pre></div></div></section>
<section class="section reveal" id="connectors"><div class="section-head"><div><div class="eyebrow">CONNECTORS / 03</div><h2 data-en="One contract.<br>Many portals." data-ar="عقد واحد.<br>بوابات متعددة.">One contract.<br>Many portals.</h2></div><p>Every installed connector declares what it can actually do. The live registry below is generated from the running platform.</p></div><div class="gallery" id="connectorGallery"><div class="empty">Loading connector registry…</div></div></section>
<section class="section reveal" id="catalog"><div class="section-head"><div><div class="eyebrow">CATALOG / 04</div><h2 data-en="The source<br>registry." data-ar="سجل<br>المصادر.">The source<br>registry.</h2></div><p>Honest access labels distinguish live records, discovery-only portals, blocked services and key-gated APIs.</p></div><div class="filters"><input class="field" id="search" aria-label="Search sources" placeholder="Search source, authority or emirate…"><select class="field" id="status" aria-label="Filter access status"><option value="">ALL ACCESS TYPES</option><option value="live">LIVE</option><option value="metadata_only">METADATA ONLY</option><option value="key_required">KEY REQUIRED</option><option value="blocked">BLOCKED</option></select></div><div class="catalog" id="sources"><div class="empty">Loading official registry…</div></div></section>
<section class="section reveal" id="datasets"><div class="section-head"><div><div class="eyebrow">DATASETS / 05</div><h2 data-en="Look before<br>you query." data-ar="افحص قبل<br>الاستعلام.">Look before<br>you query.</h2></div><p>Discover what a live portal actually exposes before requesting records or building an analysis.</p></div><div class="dataset-browser"><div class="controls"><label>Live source</label><select class="field" id="datasetSource"></select><label>Dataset search</label><input class="field" id="datasetQuery" placeholder="roads, health, عقارات…"><button class="button run" id="loadDatasets">DISCOVER DATASETS ↗</button><p class="notice">LIVE REQUEST / MAXIMUM 25 DATASETS</p></div><div class="dataset-results" id="datasetResults"><div class="empty">Choose a live source, then discover its datasets.</div></div></div></section>
<section class="section reveal" id="playground"><div class="section-head"><div><div class="eyebrow">PLAYGROUND / 06</div><h2 data-en="Query the<br>public layer." data-ar="استعلم من<br>الطبقة العامة.">Query the<br>public layer.</h2></div><p>Run safe same-origin reads and inspect the exact envelope, provenance and data-quality metadata returned to agents.</p></div><div class="workbench"><div class="controls"><label>Endpoint</label><select class="field" id="endpoint"><option value="/api/v1/coverage">Coverage summary</option><option value="/api/v1/search?q=عقارات">Hybrid search: عقارات</option><option value="/api/v1/intelligence/indicators/open_data_coverage">Indicator: coverage</option><option value="/api/v1/intelligence/recipes/source_coverage">Recipe: source coverage</option><option value="/.well-known/uaemcp.json">Trust manifest</option></select><label>Custom GET path</label><input class="field" id="custom" value="/api/v1/coverage"><button class="button run" id="run">RUN REQUEST ↗</button><p class="notice">GET ONLY / SAME ORIGIN / PUBLIC ENDPOINTS</p></div><pre class="output" id="output">Select an endpoint, then run the request.</pre></div></section>
<section class="community"><div><div class="eyebrow">OPEN SOURCE / MIT</div><h2 data-en="Build the public layer with us." data-ar="شارك في بناء طبقة البيانات العامة.">Build the public layer with us.</h2><p>Add a connector. Verify a license. Improve Arabic terminology. Build an application. Every contribution should make official data easier to inspect and harder to misrepresent.</p><div class="actions"><a class="button" href="https://github.com/ahmedvnabil/Open-Emirates-Intelligence-MCP">CONTRIBUTE ON GITHUB ↗</a><a class="button alt" href="/openapi.json">OPENAPI CONTRACT</a></div></div><div class="seal"><svg viewBox="0 0 300 300" aria-hidden="true"><defs><path id="circle" d="M150,150m-108,0a108,108 0 1,1 216,0a108,108 0 1,1 -216,0"/></defs><circle cx="150" cy="150" r="106" fill="none" stroke="#f1eddf"/><text fill="#f1eddf" font-family="IBM Plex Mono" font-size="11" letter-spacing="3"><textPath href="#circle">OPEN EMIRATES INTELLIGENCE • VERIFIED PUBLIC DATA • </textPath></text><g transform="translate(75 80) scale(3.1)"><path d="M9 32V18h4v14zm6 0V13h4v19zm6 0V20h4v12zm6 0V10h4v22zm6 0V16h4v16z" fill="#f1eddf"/><path d="M9 35h28" stroke="#173d2d" stroke-width="3"/></g></svg></div></section></main>
<footer class="footer"><span>OPEN EMIRATES INTELLIGENCE / MIT / 2026</span><span>DESIGNED &amp; MAINTAINED BY AHMED MORSY</span></footer></div>
<script>
const state={sources:[],lang:'en'};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderSources(){const q=document.querySelector('#search').value.toLowerCase(),status=document.querySelector('#status').value;const rows=state.sources.filter(s=>(!status||s.access_status===status)&&([s.id,s.name_en,s.name_ar,s.owner].join(' ').toLowerCase().includes(q)));document.querySelector('#sources').innerHTML=rows.length?rows.map((s,i)=>'<div class="source"><span class="mono">'+String(i+1).padStart(2,'0')+'</span><div><span class="source-title">'+esc(state.lang==='ar'?s.name_ar:s.name_en)+'</span><small>'+esc(s.id)+'</small></div><span class="owner">'+esc(s.owner)+'</span><span class="tag connector">'+esc(s.kind)+'</span><span class="status '+esc(s.access_status)+'">● '+esc(s.access_status.replace('_',' '))+'</span></div>').join(''):'<div class="empty">No sources match this filter.</div>'}
function renderConnectors(){const counts={};state.sources.forEach(s=>counts[s.kind]=(counts[s.kind]||0)+1);document.querySelector('#connectorGallery').innerHTML=Object.entries(counts).sort().map(([kind,count])=>'<article class="connector"><small>INSTALLED / '+count+' SOURCE'+(count===1?'':'S')+'</small><strong>'+esc(kind)+'</strong><span>Bounded · capability-aware · source-cited</span></article>').join('')}
function setupDatasetSources(){const live=state.sources.filter(s=>s.access_status==='live');document.querySelector('#datasetSource').innerHTML=live.map(s=>'<option value="'+esc(s.id)+'">'+esc(state.lang==='ar'?s.name_ar:s.name_en)+'</option>').join('')}
async function boot(){const [catalog,coverage]=await Promise.all([fetch('/api/v1/sources').then(r=>r.json()),fetch('/api/v1/coverage').then(r=>r.json())]);state.sources=catalog.data;document.querySelector('#portals').textContent=coverage.data.officialPortalsIndexed;document.querySelector('#live').textContent=coverage.data.liveRecordConnectors;renderSources();renderConnectors();setupDatasetSources()}
document.querySelector('#search').addEventListener('input',renderSources);document.querySelector('#status').addEventListener('change',renderSources);document.querySelector('#endpoint').addEventListener('change',e=>document.querySelector('#custom').value=e.target.value);
document.querySelector('#lang').addEventListener('click',()=>{state.lang=state.lang==='en'?'ar':'en';document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';document.querySelector('#lang').textContent=state.lang==='ar'?'English':'العربية';document.querySelectorAll('[data-'+state.lang+']').forEach(el=>el.innerHTML=el.dataset[state.lang]);renderSources();setupDatasetSources()});
document.querySelector('#run').addEventListener('click',async()=>{const out=document.querySelector('#output'),path=document.querySelector('#custom').value.trim();if(!path.startsWith('/api/v1/')&&!path.startsWith('/.well-known/')&&path!='/openapi.json'){out.textContent='Only local public API paths are allowed.';return}out.classList.add('loading');out.textContent='Requesting '+path+' …';try{const r=await fetch(path),body=await r.json();out.textContent='HTTP '+r.status+'\n\n'+JSON.stringify(body,null,2)}catch(e){out.textContent='Request failed: '+e.message}finally{out.classList.remove('loading')}});
document.querySelector('#loadDatasets').addEventListener('click',async()=>{const target=document.querySelector('#datasetResults'),source=document.querySelector('#datasetSource').value,q=document.querySelector('#datasetQuery').value.trim();target.innerHTML='<div class="empty">Discovering datasets…</div>';try{const r=await fetch('/api/v1/sources/'+encodeURIComponent(source)+'/datasets?limit=25'+(q?'&query='+encodeURIComponent(q):'')),body=await r.json(),rows=body.data||[];target.innerHTML=rows.length?rows.map(d=>'<article class="dataset"><strong>'+esc(state.lang==='ar'&&d.title_ar?d.title_ar:d.title_en)+'</strong><span>'+esc(d.id)+' · '+(d.records_count??'unknown')+' records · geo '+(d.has_geo?'yes':'no')+'</span></article>').join(''):'<div class="empty">No datasets returned. This source may expose one direct record stream.</div>'}catch(e){target.innerHTML='<div class="empty">Dataset discovery failed: '+esc(e.message)+'</div>'}});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('visible')),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
boot().catch(e=>document.querySelector('#sources').innerHTML='<div class="empty">Registry unavailable: '+esc(e.message)+'</div>');
</script></body></html>`;
}
